---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-rsyslog-build-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-rsyslog-build-docker-image/ci


resources:
- name: git-rsyslog-build-docker-image
  type: git
  source:
    uri: {{pipeline-git-repo}}
    private_key: {{github-access-token}}

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-hub-task-image}}
